import sys
import peppy
from Bio import SeqIO

singularity: "docker://continuumio/miniconda3"
configfile: "config/config.yaml"
pepfile: "config/pep.yaml"

SAMPLES = [x.sample_name for x in pep.samples]
SUBSAMPLE_TABLE = pep.subsample_table[0]
TES = [x.id.split("#")[0] for x in SeqIO.parse(config.get("TRANSPOSON_FASTA"), "fasta")]

MAIN_CONFIG = config.get("MAIN_CONFIG",'config/config.yaml')

subworkflow custom_genome:
    workdir:
        "../../gte21-custom-genome/"
    snakefile:
        "../../gte21-custom-genome/workflow/Snakefile"
    configfile:
        MAIN_CONFIG


rule all:
    input:
        expand('results/copies/{s}.csv',s=SAMPLES),
        "results/snps/snps.vcf",
        "results/snps/depth-at-snps.csv.gz"

rule samtools_index:
    input:
        "{file}.bam"
    output:
        "{file}.bam.bai"
    params:
        "" # optional params string
    wrapper:
        "https://github.com/snakemake/snakemake-wrappers/raw/0.70.0/bio/samtools/index"


include: "rules/trim.smk"
include: "rules/align-wgs.smk"
include: "rules/depth.smk"
include: "rules/snps.smk"
