cluster: sbatch --export=ALL --partition=genetics_1 --nodes=1 --time {resources.time} --ntasks 1 --mem {resources.mem} --cpus-per-task={resources.cpus}
default-resources: [time=20,mem=4000,cpus=1]
jobs: 1000
